import Link from 'next/link';
import { Metadata } from 'next';
import { generateMetadata as generateSEOMetadata } from '@/app/components/Metadata';

export const metadata: Metadata = generateSEOMetadata({
  title: 'Server Component Metadata',
  description: 'A test page demonstrating Next.js App Router metadata API',
  keywords: ['metadata', 'nextjs', 'server component'],
  structuredData: {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Metadata Test Page',
    description: 'Testing Next.js App Router metadata API'
  }
});

export default function TestMetadataPage() {
  return (
    <div className="container mx-auto py-8 px-4">
      <h1 className="text-2xl font-bold mb-4">Server Component Metadata Test</h1>
      <p className="mb-4">
        This page demonstrates how to use the Next.js App Router metadata API in a server component.
      </p>
      
      <div className="bg-gray-100 p-4 rounded-lg mb-6">
        <p>If you view the page source, you should see metadata tags generated by Next.js, including:</p>
        <ul className="list-disc ml-6 mt-2">
          <li>Title: "Server Component Metadata | Stayvillow"</li>
          <li>Description meta tag</li>
          <li>Keywords meta tag</li>
          <li>Open Graph tags</li>
          <li>JSON-LD structured data</li>
        </ul>
      </div>
      
      <div className="flex space-x-4">
        <Link href="/test-seo" className="text-blue-500 hover:underline">
          View Client Component SEO test
        </Link>
        <Link href="/" className="text-blue-500 hover:underline">
          Go back home
        </Link>
      </div>
    </div>
  );
} 